""" Just a little nicer to keep all this junk in a seperate file.
    This function returns a dictionary holding the Quandl codes for our chosen
    data. """


def quandl_codes():
    return {'unemployment': "UGID/UNRATE_AUS",
            'youth_unemployment': "ULMI/YUNEM_AUS",
            'ed_enrolment': "UGID/ENROL_AUS",
            'interest_rates': "UGID/IFIR_AUS",
            'inflation': "UGID/IFIR_AUS",
            'paper_manuf': "UGID/PAPR_AUS",
            'cereal_prod': "UGID/CEREAL_AUS",
            'tot_employment': "UGID/EMPTOT_AUS",
            'land_data': "UGID/LND_AUS",
            'bal_payments': "UGID/BOP_AUS",
            'gross_value_added': "UNAE/GVACD_AUS",
            'per_capita_gni': "UNAE/GNICDPC_AUS",
            'sugar_output': "UIST/OUT_SUGR_AUS",
            'plastic_output': "UIST/OUT_PLAS_AUS",
            'pharma_employees': "UIST/EMP_PHRM_AUS",
            'cement_output': "UIST/OUT_CMNT_AUS",
            'beverage_workers': "UIST/EMP_BEVS_AUS",
            'machinery_output': "UIST/OUT_MCGE_AUS",
            'rubber_employees': "UIST/EMP_RUBB_AUS",
            'printer_employees': "UIST/EMP_PRNT_AUS",
            'textile_employees': "UIST/EMP_TXTL_AUS",
            'printing_output': "UIST/OUT_PRNT_AUS",
            'coke_employees': "UIST/EMP_COKE_AUS",
            'pottery_employees': "UIST/EMP_PTRY_AUS",
            'airospace_employees': "UIST/EMP_AERO_AUS",
            'tea_production': "UINC/TEAS_AUS",
            'coke_production': "UINC/COKE_AUS",
            'alcohol_production': "UINC/ALCO_AUS",
            'wool_production': "UINC/WOOL_AUS",
            'chocolate_production': "UINC/CHOC_AUS",
            'industrial_production': "UIFS/IP_AUS",
            'banks_money': "UIFS/BK_MON_AUS",
            'export_volumes': "UIFS/BP_EVO_AUS",
            'export_prices': "UIFS/BP_EPX_AUS",
            'bond_yields': "UIFS/YLD_AUS",
            'import_values': "UIFS/BP_IVA_AUS",
            'exchange_rates': "UIFS/FX_AUS",
            'greenhouse_gas_emissions': "UGHG/AUS",
            'beehive_stock': "UFAO/LV_BEE_AUS",
            'ass_stock': "UFAO/LV_ASS_AUS",
            'avocado_production': "UFAO/CR_AVOC_AUS",
            'real_estate_prices': "BIS/RE_QAUN628",
            'house_price_change(year_on_year)': "BIS/RE_QAUN771",
            'hydro_energy': "UENG/EH_AUS",
            'uranium': "UENG/UR_AUS",
            'geothermal': "UENG/EG_AUS"
            }
